require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 100

Lint/Debugger:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*_spec.rb

RSpec/MessageChain:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false